adding input for ssh connections and sg ingress rule for aws managed nodes
nimbux911/terraform-aws-eks pull request #11
Opened 2022-06-24 17:28 UTC by qemanuel

2022-06-24 20:50 UTC, ivours approved these changes

2022-06-24 21:01 UTC, ivours requested changes
A single aws_security_group_rule for eks_worker_ingress_ssh must be created, containing all the cidr_blocks. The count attribute will act as a toggle (0/1).

2022-06-28 01:44 UTC, qemanuel commented
> A single aws_security_group_rule for eks_worker_ingress_ssh must be created, containing all the cidr_blocks. The count attribute will act as a toggle (0/1).

Fixed

2022-06-28 01:52 UTC, ivours approved these changes

2022-06-28 02:39 UTC, merged